---
- name: "Compile email account"
  ansible.builtin.command: "postmap /etc/postfix/sasl_passwd"
  register: diff_cmd
  failed_when: diff_cmd.rc != 0
  changed_when: diff_cmd.rc == 0
- name: "Compile generic map"
  ansible.builtin.command: "postmap /etc/postfix/generic"
  register: diff_cmd
  failed_when: diff_cmd.rc != 0
  changed_when: diff_cmd.rc == 0
- name: "Restart postfix"
  ansible.builtin.service:
    name: postfix
    state: restarted
    enabled: true
- name: "Send test email"
  community.general.mail:
    to: "{{ test_email_address }}"
    subject: "Test Email"
    body: "System {{ ansible_hostname }} has been successfully configured."
  when: send_test_email
